import { jsx } from "theme-ui";
import { Container, Flex, Box, Heading, Text, Image, Button } from "theme-ui";
import React, { useState } from "react";
import Privacy from "assets/privacy.svg";
export default function Policy() {

    return (
        <>
            <Container  sx={styles.banner.contentBox}>

                <Box sx={styles.banner.imageBox}>

                    {/* <Flex> */}
                    <Image src={Privacy} sx={styles.img} />
                    {/* </Flex> */}
                </Box>
            </Container>
            <Container sx={styles.banner.container}>
                <Box sx={styles.banner.contentBox}>
                    <Heading as="h1" variant="heroPrimary">
                        Privacy Policy
                    </Heading>
                </Box>
            </Container>
            <Container sx={styles.sponsorBox}>
                <Box sx={styles.banner.contentBox}>


                    <Text>
                        This TERMS OF USE POLICY is made by DJL Tutorials LLP, a registered
                        Limited Liability Partnership, bearing LLPIN AAW-3122, having its
                        registered office at Borivali West, Mumbai, Maharashtra, India
                        conducting its business of providing an online learning service to students
                        in cheaper and efficient way through its Website and App under the
                        brand name “AbhyaSetu” (hereinafter referred to as “AbhyaSetu”). This
                        document is an electronic record in terms of the Information Technology
                        Act, 2000 and rules framed there under pertaining to electronic records as
                        applicable and amended from time to time. This electronic record is
                        generated by a computer system and does not require any physical or
                        digital signatures.
                    </Text>
                    <Text>
                        This document is published on the Website and/or App in accordance
                        with the provisions of Rule 3 (1) of the Information Technology
                        (Intermediaries Guidelines) Rules, 2011 that require publishing the rules
                        and regulations, privacy policy and user agreement for access or usage of
                        the Website and/or App.
                    </Text>
                    <Text>
                        Please read the following terms and conditions very carefully as your use
                        of the Website and/or App and availing Services is subject to your
                        acceptance of and compliance with the following terms and conditions
                        including the applicable policies which are incorporated herein by way of
                        reference and as amended from time to time (the "Terms and conditions").
                    </Text>
                    <Text>
                        ACCESSING, BROWSING OR OTHERWISE USING THE WEBSITE
                        AND/OR APP INDICATES YOUR AGREEMENT TO ALL THE TERMS
                        AND CONDITIONS HEREIN, SO PLEASE READ THESE TERMS AND
                        CONDITIONS CAREFULLY BEFORE PROCEEDING. By impliedly or
                        expressly accepting these Terms and Conditions of use of the Website
                        and/or App, You also accept and agree that you have read, understood
                        and are bound by these Terms and Conditions, regardless of how you
                        subscribe to use the Services. If You do not want to be bound by the Terms
                        and Conditions, You must not use the Website and/or App or the
                        Services.
                    </Text>
                    <h3>
                        Definitions
                    </h3>
                    <Text>
                        <b> “App”</b>  means a AbhyaSetu mobile application providing Services.
                    </Text>
                    <Text>
                        "Services” means providing service of chapter wise, topic wise, paid
                        online learning facility as per structured curriculum syllabus prescribed
                        for students of various courses through the use of Website and/or App.
                    </Text>
                    <Text>
                        “Terms of Use Policy” means and includes the Terms and conditions as
                        well as Privacy Policy and Disclaimer available on the Website and/or
                        App.
                    </Text>
                    <Text>
                        “Use" or "Using" means to access, view, download, copy, or otherwise
                        benefit from using the Website and/or App.
                    </Text>
                    <Text>
                        "User" and/or “You”, means any person, who accesses or uses Website
                        and/or App for his/her own purpose or on behalf of someone else.
                    </Text>
                    <Text>
                        “Website” means www.abhyasetu.com and all web-pages appearing,
                        appended, available along with the Website.
                    </Text>
                    <h2>
                        <u>
                            <b>
                                Terms and conditions
                            </b>
                        </u>
                    </h2>
                    <h3>
                        Use of Website and/or App
                    </h3>
                    <Text>
                        The Use of this Website and/or App is subject to the Terms and conditions. By accessing and browsing this Website and/or App, You
                        unconditionally accept, without limitation or qualification, these Terms
                        and conditions. This Website and/or App, is directed for use of students
                        who may be below the age of 18 years in which case the consent by their
                        parents/legal guardians is deemed to be obtained. User represent that the
                        User possesses the legal right and ability to create binding obligations.
                        AbhyaSetu reserves the right to refuse Service, or cancel registration in its
                        sole discretion.
                    </Text>
                    <Text>
                        User is hereby allowed to use this Website and/or App subject to
                        acceptance of the Terms of Use Policy available on the Website and/or
                        App. AbhyaSetu retains the right to change the Terms of Use Policy from
                        time to time and such modification shall be immediately applicable. Every
                        time You use this Website and/or App, shall constitute your deemed
                        acceptance to the latest version of the Terms of Use Policy. User conveys
                        acceptance to Terms of Use Policy every time when the User uses this
                        Website and/or App. User has discretion not to use this Website and/or
                        App, so User's use of this Website and/or App, despite having the right
                        and power of not to use, is construed as User has accepted the Terms of
                        Use Policy. AbhyaSetu reserves the right to store, evaluate, analyze, verify
                        and authenticate the personal information and data provided by the User.
                        Any person who accesses this Website and/or App is presumed to be
                        legally capable of entering into a legal contract and has understood and
                        voluntarily accepted the Terms of Use Policy.
                    </Text>
                    <Text>
                        AbhyaSetu shall have no responsibility for any loss or damage caused to
                        You and/or your device or any other hardware and / or software and/or
                        instrument, including loss of data or effect on the processing speed,
                        resulting from Your use of AbhyaSetu's Services.
                    </Text>
                    <Text>
                        If You are "competent/capable" of contracting within the meaning of the
                        Indian Contract Act, 1872 You shall be eligible to register on the Website
                        and/or App and all Services. If you are minor, un-discharged insolvent
                        etc. You are not eligible to register for the Services. As a minor if You wish
                        to use the Services, such use shall be made available to You by Your legal
                        guardian or parents, who has agreed to these Terms. In the event a minor
                        uses the Website and/or App and/or Services, it is assumed that he/she
                        has obtained the consent of the legal guardian or parents and such use is
                        made available by the legal guardian or parents. AbhyaSetu will not be
                        responsible for any consequence that arises as a result of misuse of any
                        kind of AbhyaSetu's Website and/or App and/or Services that may occur
                        by virtue of any person including a minor registering for the Services. By
                        using the Services You warrant that all the data provided by You is
                        accurate and complete and that student using the Website and/or App
                        has obtained the consent of parent/legal guardian (in case of minors).
                        AbhyaSetu reserves the right to terminate Your subscription, account and
                        / or refuse to provide You with access to the Services if it is discovered
                        that You are under the age of 18 (eighteen) years and the consent to use
                        the Services is not made by Your parent/legal guardian or any
                        information provided by You is inaccurate. You acknowledge that
                        AbhyaSetu does not have the responsibility to ensure that You conform
                        to the aforesaid eligibility criteria. It shall be Your sole responsibility to
                        ensure that You meet the required qualification.
                    </Text>
                    <h3>
                        Rules of Conduct
                    </h3>
                    <Text>
                        The Website and/or App is to be used solely for your non-exclusive,
                        nonassignable, non-transferable and limited personal use and for no other
                        purposes. Use of the Website and/or App is subject to all applicable local,
                        state, national laws and regulations wherever applicable. User shall not
                        use, allow, or enable others to use the Website and/or App, or knowingly
                        condone use of this Website and/or App by others, in any manner that is,
                        attempts to, or is likely to:
                        <ul>
                            <li>
                                Impersonate somebody that your real entity, fake identity or any
                                combination of both or anything related to fake or improper
                                impersonation
                            </li>
                            <li>
                                be ethically not acceptable, violates laws and regulations of any
                                state, country
                            </li>
                            <li>
                                affect reputation of the Website and/or App or any other party in
                                whatsoever manner
                            </li>
                            <li>
                                send or result in the transmission of SPAM, junk e-mail, chain
                                letters, duplicative or unsolicited messages, or so-called
                                "spamming" and "phishing"
                            </li>
                            <li>
                                transmit, distribute or upload programs or materials that contain
                                malicious code, such as viruses, timebombs, worms, trojan horses,
                                spyware, or other potentially harmful programs or other material
                                or information
                            </li>
                            <li>
                                Upload/Posting any content on Website and/or App which is
                                defamatory, or violating privacy or publicity rights, or contents
                                showing or stating pornographic, discrimination on sex, religion,
                                skin color, race, nationality or any other socially undesirable
                                material
                            </li>
                            <li>
                                modify, disrupt, impair, alter or interfere with the use, features,
                                functions, operation or maintenance of the Website and/or App
                            </li>
                            <li>
                                Or any other usage in an inappropriate manner
                            </li>
                        </ul>
                    </Text>
                    <h3>
                        Cookies
                    </h3>
                    <Text>
                        AbhyaSetu may place a text file called a "cookie" in the browser files of
                        User's computer and/or mobile. The cookie itself does not contain
                        Personal Information; although it will enable the Website and/or App to
                        relate use of the Website and/or App to information that User have
                        specifically and knowingly provided to the Website and/or App. The
                        Cookies enable AbhyaSetu to remember User's choices and some data
                        field contents which User would be required to fill-in.
                    </Text>
                    <h3>
                        Advertisements / Link to Third Party Sites
                    </h3>
                    <Text>
                        AbhyaSetu may post advertisements or may provide links to third party
                        websites and/or apps as provided by advertisers and/or third parties on
                        the Website and/or App. These advertisers and/or third parties might set
                        cookies on their websites. AbhyaSetu is not responsible for any activity
                        performed by the User on the websites and/or apps of these advertisers
                        and/or third parties. User on his/her entire risk and volition is advised
                        to deal with the advertisers and/or third parties, if User intends to. By
                        allowing such advertisements and/or links to third parties, AbhyaSetu
                        does not recommend or market or warranty the advertisers' and/or third
                        parties' quality, commitment, deliverables and fitness to consumption,
                        reasonability and advertisers' and/or third parties' commitment to
                        protect User's Personal Information.
                    </Text>
                    <h3>
                        Eligibility
                    </h3>
                    <Text>
                        To register as a member of AbhyaSetu or to Use this Website and/or App,
                        you may not be adult (18 years of age completed), therefore it is implied
                        that You must have obtained a permission / consent from Your
                        parent/guardian who is an adult as per the laws of India (currently,
                        individuals having age of 18 years or above). This Website and/or App is
                        only to facilitate the Services who are legally competent to enter into an
                        agreement. By using Services, you represent & warrant that you have the
                        right, authority & legal capacity to enter into this agreement.
                    </Text>
                    <h3>
                        Registration
                    </h3>
                    <Text>
                        We expect that you would complete the registration process with fairness
                        and honesty while furnishing your personal information to AbhyaSetu.
                        Your personal details submitted by you on the Website and/or App shall
                        be true and correct. You accept that you will be responsible for any
                        information provided to AbhyaSetu. If at any point of time, AbhyaSetu
                        comes to know or is informed by any third party or has reasons to believe
                        that any information provided by you at the time of registration or
                        otherwise is untrue, then AbhyaSetu has the right to terminate your
                        membership and/or block you from using the Services provided by
                        AbhyaSetu. AbhyaSetu’s Service is restricted strictly to the registered
                        member.
                    </Text>
                    <Text>
                        Before using the Website and/or App, the User is required to register
                        himself/herself by following a simple registration process. When the User
                        first time visits the Website and/or App, on his/her screen, he/she shall
                        click on a tab namely “Register”. The User shall provide his mobile
                        number which will then be verified by One Time Password (OTP). Upon
                        submission of OTP and successful verification, the User will be directed
                        to registration page wherein the User shall feed Name, E-mail ID. Once
                        the registration process is completed a message will be displayed on the
                        screen as “the registration process is completed successfully” and
                        thereafter User will be directed to the home page of the Website and/or
                        App.
                    </Text>
                    <h3>
                        Payments
                    </h3>
                    <Text>
                        AbhyaSetu offers you only online payment option. Online Payment
                        Modes available will be Credit Cards, Debit Cards, Net Banking, UPI.
                    </Text>
                    <Text>
                        Acceptance: We accept payments made by most of the major credit/debit
                        cards issued in India. Acceptance of card payment is at the sole discretion
                        of AbhyaSetu and you may be asked to submit copy of photo identity
                        proof too. However, AbhyaSetu reserves its right to deny acceptance of
                        card payment without any prior notice.
                    </Text>
                    <Text>
                        You may pay on our Website and/or App and choose any of payment
                        modes made available to you by the payment gateway. Payments will be
                        processed if you have selected your preferred/desired chapter available
                        with AbhyaSetu. AbhyaSetu may set or change amounts per chapter
                        without prior intimation to User.
                    </Text>
                    <Text>
                        Payment: While availing any of the payment method/s available on the
                        Website and/or App, we will not be responsible or assume any liability,
                        whatsoever in respect of any loss or damage arising directly or indirectly
                        to you due to:
                        <ol type="i">
                            <li>
                                Lack of authorization for any transaction/s, or
                            </li>
                            <li>
                                Exceeding the present limit mutually agreed by you and your
                                issuing bank, or iii. Any payment issues arising out of the transaction,
                                or iv. Decline of transaction for any other reason/s
                            </li>
                        </ol>
                    </Text>
                    <Text>
                        Prices stated at the time of making payment for the opted chapter shall
                        apply in respect to that chapter only
                    </Text>
                    <Text>
                        You represent and confirm that the credit/debit card that is being used is
                        yours or that you have been specifically authorized by the owner of the
                        credit/debit card to use it. You further agree and undertake to provide
                        the correct and valid credit card details to carry out a transaction on the
                        Website and/or App. All credit/debit card holders are subject to
                        validation checks and authorization by the card issuer. If the issuer of
                        your payment card refuses to authorize payment to us, we will not be
                        liable for any delay or not providing Services.
                    </Text>
                    <Text>
                        AbhyaSetu reserves its right to refuse to process transactions by Users
                        with a prior history of questionable charges including without limitation
                        to breach of any agreements by User with AbhyaSetu or breach/violation
                        of any law or any charges imposed by bank or breach of any policy.
                        AbhyaSetu may do such checks as it deems fit before approving the User's
                        payment for security or other reasons at the discretion of AbhyaSetu. As
                        a result of such check if AbhyaSetu is not satisfied with the creditability
                        of the User or genuineness of the transaction, it will have the right to reject
                        such payment. AbhyaSetu may cancel any transaction at its sole
                        discretion, if AbhyaSetu is suspicious of any User's authenticity or activity
                        or if the User is conducting high transaction volumes, to ensure safety of
                        the transaction
                    </Text>
                    <Text>
                        In cases where the online payment for the Services does not get
                        successfully communicated to our system due to any network or technical
                        issue between intermediary, bank or payment gateway, the Services shall
                        not be processed and a refund will be initiated for the same. However, in
                        an unsuccessful attempt if the User’s account gets debited, such amounts
                        generally gets auto reversed in the same account. However, AbhyaSetu
                        shall not be held responsible for such amounts debited in unsuccessful
                        attempts and User can raise reversal request with their bank should there
                        be any unreasonable delay in refund.
                    </Text>
                    <Text>
                        User acknowledges that AbhyaSetu will not be liable for any damages,
                        interests, claims etc. resulting from not processing a transaction or any
                        delay in processing a transaction which is beyond control of AbhyaSetu.
                    </Text>
                    <Text>
                        Set-off: In case the User has availed any benefit in relation to the Services
                        for which the payment has been cancelled by the User, he/she agrees and
                        authorizes AbhyaSetu to recover such benefits from the User or set-off the
                        same from any refunds to the User.
                    </Text>
                    <Text>
                        AbhyaSetu and You understand that if you have paid on the Website
                        and/or App for desired Services it means that you have chosen the
                        desired chapter. You agree that, once the payments are credited to
                        AbhyaSetu you cannot change the chapters you have paid for in exchange
                        of any other chapter you would like to opt, you further agree that you
                        shall pay separately for any such chapters. You acknowledge that once
                        you have paid for the Services, the same cannot be refunded in any case
                        by AbhyaSetu.
                    </Text>
                    <h3>
                        Services:

                    </h3>
                    <Text>
                        All Services and information displayed on Website and/or App constitute
                        an "invitation to offer". Your request for purchase constitutes your "offer".
                        All requests placed by you on the Website and/or App are subject to
                        acceptance by us and conditional on your acceptance and adherence to
                        the Terms of Use Policy.
                    </Text>
                    <Text>
                        AbhyaSetu may alert you by email or phone (through sms/call) to inform
                        you about new service offerings of AbhyaSetu and its
                        subsidiaries/affiliates or other information which AbhyaSetu feel might
                        be useful for you, through AbhyaSetu or its subsidiaries/affiliates.
                    </Text>
                    <h3>
                        Exactness / Accuracy of Services:
                    </h3>
                    <Text>
                        We have made significant efforts to accurately provide current, correct,
                        and clearly display the topics and concepts covered as per the school
                        syllabus prescribed for the students of various courses which appear on
                        the Website and/or App. However, we do not warrant/guarantee that
                        the Services or other content of this Website and/or App is accurate,
                        complete, reliable, current, or error-free. The particular technical
                        specifications and settings of your computer and its display could affect
                        the accuracy of Services offered on this Website and/or App.
                    </Text>
                    <h3>
                        Following points have to be noted in accordance with the provisions of
                        Rule 3 (2) of the Information Technology (Intermediaries Guidelines)
                        Rules, 2011:
                    </h3>
                    <Text>
                        User is not entitled to host, display, upload, modify, publish, transmit,
                        update or share any information on the Website and/or App that -
                        < ol type="A">
                            <li>
                                belongs to another person and to which the User does not have any
                                right to;
                            </li>
                            <li>
                                is grossly harmful, harassing, blasphemous defamatory, obscene,
                                pornographic, pedophilic, libelous, invasive of another's privacy,
                                hateful, or racially, ethnically objectionable, disparaging, relating or
                                encouraging money laundering or gambling, or otherwise unlawful
                                in any manner whatever;
                            </li>
                            <li>
                                harm minors in any way;
                            </li>
                            <li>
                                infringes any patent, trademark, copyright or other proprietary
                                rights;
                            </li>
                            <li>
                                deceives or misleads the addressee about the origin of such
                                messages or communicates any information which is grossly
                                offensive or menacing in nature;
                            </li>
                            <li>
                                impersonate another person;
                            </li>
                            <li>
                                contains software viruses or any other computer code, files or
                                programs designed to interrupt, destroy or limit the functionality of
                                any computer resource;
                            </li>
                            <li>
                                threatens the unity, integrity, defense, security or sovereignty of
                                India, friendly relations with foreign states, or public order or
                                causes incitement to the commission of any cognizable offence or
                                prevents investigation of any offence or is insulting any other
                                nation.
                            </li>
                        </ol>
                    </Text>
                    <h3>
                        User's Liability:
                    </h3>
                    <Text>
                        The User hereby affirms that the information provided by him / her is
                        true, correct and complete to the best of his / her knowledge and belief.
                        The User agrees and understands that he / she will be solely responsible
                        in the event of any inaccuracy or deviation therefrom at a later stage.
                    </Text>
                    <Text>
                        You agree to comply with all applicable laws in connection with your use
                        of the Website and/or App, and such further limitations as may be set
                        forth in any written or on-screen notice from us
                    </Text>
                    <Text>
                        You, as a User, understand that upon initiating a transaction you are
                        entering into a legally binding and enforceable contract with AbyaSetu to
                        purchase the Services from AbhyaSetu and pay the transaction price to
                        AbhyaSetu using appropriate Payment Facility. You, as a User,
                        understand that all the payment facility may not be available in full or in
                        part for certain category of Services and for certain locations and hence
                        you may not be entitled to use that Payment Facility in respect of the
                        transactions for those Services or locations.
                    </Text>
                    <Text>
                        In the event of Your breach of these Terms and conditions, You agree that
                        AbhyaSetu will be irreparably harmed and may not have an adequate
                        remedy in money or damages. AbhyaSetu therefore, shall be entitled in
                        such event to obtain an injunction against such a breach from any court of
                        competent jurisdiction. AbhyaSetu's right to obtain such relief shall not
                        limit its right to obtain other remedies.
                    </Text>
                    <h3>
                        Grievance/Complaints
                    </h3>
                    <Text>
                        Please feel free to provide your concerns through any of the following
                        mediums:
                        <div>
                            Email ID: djltutorials2021@gmail.com
                        </div>
                        <div>
                            Contact No: +91 8369625078
                        </div>
                        <div>
                            Postal Address:  13/A Mangalesh CHS
                            Kastur park, Borivali West, Mumbai 400092
                        </div>
                    </Text>
                    <h3>
                        Limitation of Liability
                    </h3>
                    <Text>
                        In no event AbhyaSetu shall be liable for any special, indirect, incidental,
                        consequential or exemplary damages including but not limited to,
                        damages for loss of profits, goodwill, use, data or other intangible losses
                        arising out of or in connection with the Website and/or App, its Services
                        whatsoever, whether in an action of contract, negligence or other tortious
                        action.
                    </Text>
                    <Text>
                        Without prejudice to the generality of this section the total liability of
                        AbhyaSetu to you for all liabilities arising out of these Terms and
                        conditions be it in tort or contract is limited to the value of the Services
                        availed by you.
                    </Text>
                    <h3>
                        Termination
                    </h3>
                    <Text>
                        These Terms and conditions shall be effective from the date and time of
                        your acceptance of these Terms and conditions and remain in force unless
                        and until terminated by either of us. You may terminate these Terms and
                        conditions at any time, provided that you discontinue any further use of
                        this Website and/or App. We may terminate your right to access to this
                        Website and/or App at any time and may do so immediately without
                        notice, and such termination will be without any liability to us. Any such
                        termination event shall not cancel your obligation to pay for the Services
                        already availed or affect any liability that may have arisen under these
                        Terms and conditions.
                    </Text>
                    <h3>
                        Waiver
                    </h3>
                    <Text>
                        Our failure to enforce any provision of these Terms and conditions or
                        respond to a breach by you shall not in any way waive our right to enforce
                        subsequently any provision of these Terms and conditions or to act with
                        respect to similar breaches.
                    </Text>
                    <h3>
                        Reserved Rights of AbhyaSetu
                    </h3>
                    <Text>
                        We may discontinue this Website and/or App at any time and for any
                        reason, without notice. All rights not expressly granted herein are hereby
                        reserved to us.
                    </Text>
                    <h3>
                        Applicable Law
                    </h3>
                    <Text>
                        Any dispute arising out of the Terms of Use Policy and/or your use of the
                        Website and/or App shall be governed and construed in accordance with
                        the laws of India, notwithstanding any conflicts of law.
                    </Text>
                    <h3>
                        Jurisdiction
                    </h3>
                    <Text>
                        You specifically consent to submit any dispute arising out of the Terms of
                        Use Policy or any other policies on the Website and/or App to the
                        jurisdiction of courts of Mumbai, India.
                    </Text>
                    <h3>
                        Indemnification
                    </h3>
                    <Text>
                        You agree to indemnify, defend and hold AbhyaSetu, its partners,
                        affiliates, successors, assigns and licensors, franchisees or sub-franchisees,
                        any of their respective officers, employees, agents, vendors, licensors,
                        representatives, advertisers, service providers and suppliers harmless
                        from and against any and all claims, actions, losses, expenses, damages
                        and costs (including reasonable attorneys' fees), resulting from any breach
                        or violation of Terms and conditions by you, or due to your activities
                        related to the Website and/or App.
                    </Text>
                    <h3>
                        General provisions
                    </h3>
                    <Text>
                        Each part of this Terms of Use Policy or any other policies on the Website
                        and/or App is independent of each other. If any part of this Terms of Use
                        Policy or any other policies on the Website and/or App is found void and
                        unenforceable, it will not affect the validity of the balance of the Terms of
                        Use Policy or any other policies on the Website and/or App, which shall
                        remain valid and enforceable according to its terms.
                    </Text>
                    <h3>
                        Changes to Terms of Use Policy
                    </h3>
                    <Text>
                        AbhyaSetu have and continues to have the right to modify, change or
                        update Terms of Use Policy and any other policies on the Website and/or
                        App at any time. However, AbhyaSetu will use User’s Personal
                        Information in a manner consistent with Privacy Policy at the time User
                        shared Personal Information. User is encouraged to check the Website
                        and/or App often to get updated about Terms of Use Policy and all other
                        policies on the Website and/or App. User acknowledges that by virtue of
                        usage of the Website and/or App you provide acceptance of the Terms of
                        Use Policy and changes made to it.
                        <h4>
                            Contact information
                        </h4>
                        <div>
                            Email: djltutorials2021@gmail.com
                        </div>
                        <div>
                            Phone: +91 83696 25078
                        </div>
                        <div>
                            Address: 13/A Mangalesh CHS
                            Kastur park, Borivali West, Mumbai 400092
                        </div>
                    </Text>
                </Box>

            </Container>
        </>
    )
}

const styles = {
    banner: {
        overflow: ["hidden", "initial", null, "hidden"],
        backgroundSize: "cover",
        borderBottomRightRadius: [100, 150, null, null, null, 250],
        pt: ["150px", null, null, null, null, null, "140px", "130px"],
        pb: ["100px", null, null, "110px", null, 10, "150px"],
        backgroundColor: "primary",
        container: {
            display: "flex",
        },
        contentBox: {
            width: ["100%", null, "85%", "55%", "50%", "55%"],
            display: "flex",
            flexDirection: "column",
            alignItems: "flex-start",
            margin: ["auto 0", "auto 0", "auto 7%", "auto 20%", "auto 25%", "auto 20%"],
            flexShrink: 0,
            pt: [0, null, null, null, null, null, 5, 7],
        },


    },
    sponsorTitle: {
        color: "white",
        fontSize: [1, 2],
        opacity: 0.6,
        pr: 20,
        flexShrink: 0,
        pb: [2, null, 0],
    },
    sponsorBox: {
        // pt: ["35px", null, null, null, null, "45px"],

        flexDirection: ["column", null, "row"],
        sponsor: {
            display: "flex",
            alignItems: "center",
            // "> a": {
            //     mr: [5, null, null, 4, 6],
            //     display: "flex",
            //     "&:last-of-type": {
            //         mr: 0,
            //     },
            // },
        },
    },
};